version: '3'
services:
    db_master:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: DD.08.dd
            MYSQL_DATABASE: wordpress
            MYSQL_USER: admin
            MYSQL_PASSWORD: DD.08.dd
        volumes:
            - ./my.cnf:/etc/my.cnf
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 500M
                reservations:
                    cpus: '0.25'
                    memory: 200M


    db_slave:
        image: mysql:5.7
        restart: always
        links:
            - db_master:db_master
        environment:
            MYSQL_ROOT_PASSWORD: DD.08.dd
            MYSQL_DATABASE: wordpress
            MYSQL_USER: admin
            MYSQL_PASSWORD: DD.08.dd
        volumes:
            - ./my.cnf_slave:/etc/my.cnf
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 500M
                reservations:
                    cpus: '0.25'
                    memory: 200M


    web_master:
        image: wordpress
        restart: always
        links:
            - db_master:db_master
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db_master
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: admin
            WORDPRESS_DB_PASSWORD: DD.08.dd
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 500M
                reservations:
                    cpus: "0.25"
                    memory: 200M
    web_slave:
        image: wordpress
        restart: always
        links:
            - db_master:db_master
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db_master
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: admin
            WORDPRESS_DB_PASSWORD: DD.08.dd
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 500M
                reservations:
                    cpus: "0.25"
                    memory: 200M


    haproxy_node1:
        image: haproxy
        restart: always
        links:
            - web_master:web_master
            - web_slave:web_slave
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
            - 80:8888
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 500M
                reservations:
                    cpus: "0.25"
                    memory: 200M
